name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: npm install, build
        run: |
          npm install --include=dev
          npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.10.x
          lhci autorun